name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          git clone https://github.com/grafana/grafana.git --branch v8.1.x
          cd grafana
          git revert --no-commit d74d4d6be9122cfcb81c1840972a199397952cbb
          git revert --no-commit bb1dac3c7201e1a8b3bc7def7fdc355c1830623a
          rm -Rf .git
          
      - name: Docker Package Registry
        uses: craftech-io/package-action@v3.1.0
        with:
          dockerfile: Dockerfile.ubuntu
          image_name: grafana
          access_token:  ${{ secrets.GITHUB_TOKEN }}
          tags: latest


